//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public int Quantity { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public decimal TotalPrice { get; set; }
        public string ItemName { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
